import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className="bg-blue-600 text-white py-4 shadow-md">
          <nav className="container mx-auto flex justify-between">
            <h1 className="text-xl font-bold">ELO Decision Maker</h1>
            <div>
              <a href="/" className="mr-4 hover:underline">
                Home
              </a>
              <a href="/rankings" className="hover:underline">
                Rankings
              </a>
            </div>
          </nav>
        </header>
        <main className="container mx-auto flex-grow py-8">{children}</main>
        <footer className="bg-gray-800 text-white py-4 text-center">
          <p>&copy; 2025 ELO Decision Maker</p>
        </footer>
      </body>
    </html>
  );
}
